version: '3.4'
services:
  # prerender container
  prerender-prod:
    restart: always
    build:
      context: prerender
    ports:
      - "4000:3000"

  # back-end api built with golang
  golang-prod:
    restart: always
    image: registry-host:5001/ecomerce/golang-prod:${SHA}
    ports:
      - "5001:5001"
    env_file: .env

  # worker
  worker-prod:
    network_mode: host
    image: registry-host:5001/ecomerce/worker-prod:${SHA}
    env_file: .env

  # front-end built with react
  react-prod:
    restart: always
    image: registry-host:5001/ecomerce/react-prod:${SHA}
    ports:
      - "3000:3000"
